### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by KirillRas1** [KirillRas1/ChatgptForumDjango#1]
- [x] Post creation screen
- [x] Algorithm of score based prompting, together with post options to choose one of the mods.
- [x] Fix logout button
- [x] Show modal of login when getting 401
- [x] Rework auth
- [x] Do "saved posts" and "saved comments" screens
- [x] Try to add parent comment to comments to create comment chains
- [x] Add filtering and ordering to posts and comment screens
- [x] Add tags
- [x] Pagination to comments and posts
